services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 10

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superuser1
      - POSTGRES_DB=devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superuser", "-d", "devdb"]
      interval: 2s
      timeout: 1s
      retries: 10

  rest_api:
    build:
      context: ./backend
      dockerfile: rest_api/Dockerfile
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/rest_api/development.env
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=pretty
    volumes:
      - ./backend/rest_api:/app

  ws_gateway:
    build:
      context: ./backend
      dockerfile: ws_gateway/Dockerfile
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/ws_gateway/development.env
    environment:
      - ENVIRONMENT=development
      - GRPC_HOST=ws_gateway
      - LOG_FORMAT=pretty
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/ws_gateway:/app

  event_consumer:
    build:
      context: ./backend
      dockerfile: event_consumer/Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - ENVIRONMENT=development
      - LOG_FORMAT=pretty
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/event_consumer:/app

  lease_manager:
    build:
      context: ./backend
      dockerfile: lease_manager/Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - ENVIRONMENT=development
      - LOG_FORMAT=pretty
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/lease_manager:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # edge nginx: LOCAL ENTRYPOINT
  edge:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    depends_on:
      - rest_api
      - ws_gateway
      - frontend
    volumes:
      - ./nginx/edge.dev.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
