"""Sync 8 24 2025

Revision ID: 4fd46a8f4dd1
Revises: 
Create Date: 2025-08-24 20:28:21.721522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fd46a8f4dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_invites_guild_id'), table_name='guild_invites')
    op.drop_index(op.f('ix_guild_invites_invite_id'), table_name='guild_invites')
    op.drop_index(op.f('ix_guild_invites_user_id'), table_name='guild_invites')
    op.drop_table('guild_invites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guilds_description'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_id'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_owner_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_guild_members_guild_id'), table_name='guild_members')
    op.drop_index(op.f('ix_guild_members_status'), table_name='guild_members')
    op.drop_index(op.f('ix_guild_members_user_id'), table_name='guild_members')
    op.drop_table('guild_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_members',
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'BANNED', name='guildmemberstatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('guild_members_pkey'))
    )
    op.create_index(op.f('ix_guild_members_user_id'), 'guild_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_guild_members_status'), 'guild_members', ['status'], unique=False)
    op.create_index(op.f('ix_guild_members_guild_id'), 'guild_members', ['guild_id'], unique=False)
    op.create_table('guilds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='guilds_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_guilds_owner_id'), 'guilds', ['owner_id'], unique=False)
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=False)
    op.create_index(op.f('ix_guilds_id'), 'guilds', ['id'], unique=False)
    op.create_index(op.f('ix_guilds_description'), 'guilds', ['description'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('guild_invites',
    sa.Column('invite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('guild_invites_guild_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('guild_invites_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('guild_invites_pkey'))
    )
    op.create_index(op.f('ix_guild_invites_user_id'), 'guild_invites', ['user_id'], unique=False)
    op.create_index(op.f('ix_guild_invites_invite_id'), 'guild_invites', ['invite_id'], unique=False)
    op.create_index(op.f('ix_guild_invites_guild_id'), 'guild_invites', ['guild_id'], unique=False)
    # ### end Alembic commands ###
