"""guild invite inviter

Nullable and deliberately not backfilled: invites that predate the column have
no honest answer, and the recipient's list outer-joins the inviter so they still
appear. `ondelete=SET NULL` because a deleted account must not take a valid
invitation with it.

Revision ID: 7b3ae40c0ded
Revises: c7e93a15d840
Create Date: 2026-08-14 22:19:48.446251

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '7b3ae40c0ded'
down_revision: Union[str, None] = 'c7e93a15d840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_invites', sa.Column('inviter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_guild_invites_inviter_id'), 'guild_invites', ['inviter_id'], unique=False)
    op.create_foreign_key(op.f('fk_guild_invites_inviter_id_users'), 'guild_invites', 'users', ['inviter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_guild_invites_inviter_id_users'), 'guild_invites', type_='foreignkey')
    op.drop_index(op.f('ix_guild_invites_inviter_id'), table_name='guild_invites')
    op.drop_column('guild_invites', 'inviter_id')
    # ### end Alembic commands ###
