"""initial schema

Revision ID: eba118b7a32f
Revises: 
Create Date: 2026-08-14 03:00:44.260649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'eba118b7a32f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friend_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_friend_requests_from_user_id_users')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_friend_requests_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_requests'))
    )
    op.create_index(op.f('ix_friend_requests_from_user_id'), 'friend_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_id'), 'friend_requests', ['id'], unique=False)
    op.create_index(op.f('ix_friend_requests_to_user_id'), 'friend_requests', ['to_user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('user_1_id', sa.UUID(), nullable=False),
    sa.Column('user_2_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], name=op.f('fk_friendships_user_1_id_users')),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], name=op.f('fk_friendships_user_2_id_users')),
    sa.PrimaryKeyConstraint('user_1_id', 'user_2_id', name=op.f('pk_friendships'))
    )
    op.create_index(op.f('ix_friendships_user_1_id'), 'friendships', ['user_1_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_2_id'), 'friendships', ['user_2_id'], unique=False)
    op.create_table('guilds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_guilds_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guilds'))
    )
    op.create_index(op.f('ix_guilds_description'), 'guilds', ['description'], unique=False)
    op.create_index(op.f('ix_guilds_id'), 'guilds', ['id'], unique=False)
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=False)
    op.create_index(op.f('ix_guilds_owner_id'), 'guilds', ['owner_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('DM', 'GUILD_TEXT', 'GUILD_VOICE', name='channeltype'), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_channels_guild_id_guilds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_description'), 'channels', ['description'], unique=False)
    op.create_index(op.f('ix_channels_guild_id'), 'channels', ['guild_id'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_index(op.f('ix_channels_type'), 'channels', ['type'], unique=False)
    op.create_table('guild_invites',
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_invites_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_guild_invites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_guild_invites'))
    )
    op.create_index(op.f('ix_guild_invites_guild_id'), 'guild_invites', ['guild_id'], unique=False)
    op.create_index(op.f('ix_guild_invites_invite_id'), 'guild_invites', ['invite_id'], unique=False)
    op.create_index(op.f('ix_guild_invites_user_id'), 'guild_invites', ['user_id'], unique=False)
    op.create_table('guild_members',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'BANNED', name='guildmemberstatus'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'MEMBER', name='guildmemberrole'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_members_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_guild_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_guild_members'))
    )
    op.create_index(op.f('ix_guild_members_guild_id'), 'guild_members', ['guild_id'], unique=False)
    op.create_index(op.f('ix_guild_members_role'), 'guild_members', ['role'], unique=False)
    op.create_index(op.f('ix_guild_members_status'), 'guild_members', ['status'], unique=False)
    op.create_index(op.f('ix_guild_members_user_id'), 'guild_members', ['user_id'], unique=False)
    op.create_table('channel_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_members_channel_id_channels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_members'))
    )
    op.create_index(op.f('ix_channel_members_channel_id'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_members_id'), 'channel_members', ['id'], unique=False)
    op.create_index(op.f('ix_channel_members_user_id'), 'channel_members', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_messages_channel_id_channels')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_channel_members_user_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_channel_id'), table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index(op.f('ix_guild_members_user_id'), table_name='guild_members')
    op.drop_index(op.f('ix_guild_members_status'), table_name='guild_members')
    op.drop_index(op.f('ix_guild_members_role'), table_name='guild_members')
    op.drop_index(op.f('ix_guild_members_guild_id'), table_name='guild_members')
    op.drop_table('guild_members')
    op.drop_index(op.f('ix_guild_invites_user_id'), table_name='guild_invites')
    op.drop_index(op.f('ix_guild_invites_invite_id'), table_name='guild_invites')
    op.drop_index(op.f('ix_guild_invites_guild_id'), table_name='guild_invites')
    op.drop_table('guild_invites')
    op.drop_index(op.f('ix_channels_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_guild_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_description'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_guilds_owner_id'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_id'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_description'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_friendships_user_2_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_1_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_to_user_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_from_user_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
