name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - eshan-dev-branch
      - samir-dev-branch
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Pytest
    runs-on: [self-hosted, python]  # 👈 Use your Docker runner label

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (optional if image already has it)
      - name: Ensure pip is up to date
        run: python -m pip install --upgrade pip

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Pytest
        run: python -m pytest
